name: Android Instrumentation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android_test:
    name: Running Android Tests
    runs-on: macos-13
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Install dependencies and Maestro
      - name: Install dependencies and Maestro
        run: |
          export MAESTRO_VERSION=1.39.0
          curl -Ls "https://get.maestro.mobile.dev" | bash
          arch -arm64 brew tap facebook/fb
          arch -arm64 brew install facebook/fb/idb-companion
          arch -arm64 brew install jq

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: Nexus 4
          emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
          script: |
            adb wait-for-device
            adb shell input keyevent 82

      - name: Install APK on Emulator
        run: |
          adb install ./wikipedia.apk

      - name: Run Maestro UI tests
        run: |
          export PATH="$PATH:$HOME/.maestro/bin"
          DEVICE_ID=$(adb devices | grep emulator | cut -f 1)
          maestro --device $DEVICE_ID test android-flow.yaml
