name: Android E2E Tests

on: [push, pull_request]

jobs:
  run_android_e2e:
    timeout-minutes: 10
    runs-on: macos-12

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 2: Install dependencies and Maestro
      - name: Install dependencies and Maestro
        run: |
          export MAESTRO_VERSION=1.39.0
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH:$HOME/.maestro/bin"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          profile: pixel_3a
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            
            adb install wikipedia.apk
            
            DEVICE_ID=$(adb devices | grep emulator | cut -f 1)
            export PATH="$PATH:$HOME/.maestro/bin"
            maestro --device $DEVICE_ID test android-flow.yaml

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: E2E Report
          path: |
            ${{ github.workspace }}/*.mp4
            ${{ github.workspace }}/*.png
            ${{ github.workspace }}/report*.xml
            ~/.maestro/tests/**/*
