name: Run Maestro UI Tests on Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: macos-latest  # macOS runner is needed for Android emulator support

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies and Maestro CLI
    - name: Install dependencies and Maestro
      run: |
        export MAESTRO_VERSION=1.39.0
        curl -Ls "https://get.maestro.mobile.dev" | bash
        arch -arm64 brew install jq

    # Step 3: Set up JDK 11 (required by Maestro and Android emulator)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Step 4: Set up Android Emulator (API Level 29 for testing)
    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86_64
        ram-size: 2048M
        target: default
        cores: 2
        avd-name: test
        force-avd-creation: true
        emulator-boot-timeout: 600
        emulator-port: 5554
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        disable-animations: true
        disable-spellchecker: false
        disable-linux-hw-accel: auto
        enable-hw-keyboard: false
        channel: stable
      env:
        JAVA_HOME: /Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.25-9/x64/Contents/Home

    # Step 5: Wait for emulator to be fully ready
    - name: Wait for Emulator to be ready
      run: |
        # Wait until the emulator is booted and ready to accept ADB commands
        adb -s emulator-5554 wait-for-device
        adb shell getprop sys.boot_completed | grep -m 1 '1'

    # Step 6: Install the APK on the emulator (Wikipedia APK)
    - name: Install Wikipedia APK on emulator
      run: |
        # Install the APK on the Android Emulator
        adb -s emulator-5554 install -r wikipedia.apk

    # Step 7: Run Maestro UI tests on Android Emulator
    - name: Run Maestro UI tests on Android
      run: |
        # Set PATH for Maestro
        export PATH="$PATH:$HOME/.maestro/bin"
        # Run Maestro tests (using android-flow.yaml for Android tests)
        maestro --device android test android-flow.yaml
