name: Run Maestro UI Tests on Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: macos-latest  # macOS runner is needed for Android emulator support

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies and Maestro CLI
    - name: Install dependencies and Maestro
      run: |
        export MAESTRO_VERSION=1.39.0
        curl -Ls "https://get.maestro.mobile.dev" | bash
        arch -arm64 brew install jq

    # Step 3: Set up JDK 11 (required by Maestro and Android emulator)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Step 4: Set up Android Emulator (API Level 29 for testing)
    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86_64
        ram-size: 2048M
        target: default
        # Optional: specify additional options like screen size, etc.
    
    # Step 5: Kill and restart the ADB server (to fix connection issues)
    - name: Restart ADB server
      run: |
        # Kill any running ADB server and start a new one
        adb kill-server
        adb start-server

    # Step 6: Install the APK on emulator (Wikipedia APK)
    - name: Install Wikipedia APK on emulator
      run: |
        # Wait for the emulator to fully boot up
        adb wait-for-device
        # Install the Wikipedia APK on the Android Emulator
        adb install -r wikipedia.apk

    # Step 7: Run Maestro UI tests on Android Emulator
    - name: Run Maestro UI tests on Android
      run: |
        # Set PATH for Maestro
        export PATH="$PATH:$HOME/.maestro/bin"
        # Run Maestro tests (using android-flow.yaml for Android tests)
        maestro --device android test android-flow.yaml
