name: Run UI Tests with Maestro

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run UI Tests with Maestro
        uses: theolm/maestro-run@v0.3.1-alpha
        with:
          apk-path: './wikipedia.apk'
          test-path: './android-advanced-flow.yaml'
          report-name: 'wikipedia-ui-test-report'
          record: 'true'
